### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by AotoriChiaki** [Equim-chan/tensoul#5]
在config.js中填入了base: 'https://game.maj-soul.com/1' 和access_token以后执行pnpm install和node .，遇到了下面的报错，请问是什么地方搞错了？

> {
>   version: '0.10.227.w',
>   liqiVersion: 'v0.10.226.w',
>   liqi: { nested: { lq: [Object] } },
>   serviceDiscoveryServers: [
>     'https://lb-hw.maj-soul.com/api/v0/recommend_list',
>     'https://lb-v2.maj-soul.com/api/v0/recommend_list',
>     'https://lb-cdn.maj-soul.com/api/v0/recommend_list',
>     'https://lb-hw.maj-soul.com/api/v0/recommend_list',
>     'https://lb-sy.maj-soul.com/api/v0/recommend_list'
>   ]
> }
> using wss://gateway-cdn.maj-soul.com:443
> node:events:491
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Unexpected server response: 405
>     at ClientRequest.<anonymous> (/root/tensoul/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/websocket.js:783:7)
>     at ClientRequest.emit (node:events:513:28)
>     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:701:27)
>     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
>     at TLSSocket.socketOnData (node:_http_client:542:22)
>     at TLSSocket.emit (node:events:513:28)
>     at addChunk (node:internal/streams/readable:324:12)
>     at readableAddChunk (node:internal/streams/readable:297:9)
>     at Readable.push (node:internal/streams/readable:234:10)
>     at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
> Emitted 'error' event on MJSoul instance at:
>     at WebSocket.<anonymous> (/root/tensoul/node_modules/.pnpm/mjsoul@2.3.0/node_modules/mjsoul/mjsoul.js:49:39)
>     at WebSocket.emit (node:events:513:28)
>     at abortHandshake (/root/tensoul/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/websocket.js:956:15)
>     at ClientRequest.<anonymous> (/root/tensoul/node_modules/.pnpm/ws@7.5.9/node_modules/ws/lib/websocket.js:783:7)
>     [... lines matching original stack trace ...]
>     at addChunk (node:internal/streams/readable:324:12)
> 
> Node.js v18.16.0

**Comment by acehinnnqru** [comment]
Hi，你有解决这个问题了么？

**Comment by AotoriChiaki** [comment]
没解决，最后是用的maji reviewer做的转换

**Comment by acehinnnqru** [comment]
您说的是这个吗? https://github.com/Equim-chan/mjai-reviewer/blob/master/mjsoul.adoc?
通过自己再写点工具来批量下载吗?

**Comment by AotoriChiaki** [comment]
是的
